"""
Google Ads API client for MowDirect reporting.

Usage:
    from scripts.google_ads_client import GoogleAdsClient
    from datetime import date

    client = GoogleAdsClient()
    rows = client.get_campaign_spend(date(2026, 3, 1), date(2026, 3, 31))

Reads from .env:
    GOOGLE_ADS_DEVELOPER_TOKEN
    GOOGLE_ADS_CLIENT_ID
    GOOGLE_ADS_CLIENT_SECRET
    GOOGLE_ADS_REFRESH_TOKEN     # generated by scripts/google_ads_auth.py
    GOOGLE_ADS_CUSTOMER_ID       # 10-digit ID, no dashes
    GOOGLE_ADS_LOGIN_CUSTOMER_ID # optional, only if calls are made via a manager (MCC)

Token refresh is handled automatically. The refresh token is long-lived; the
short-lived access token is refreshed silently on expiry.

API docs: https://developers.google.com/google-ads/api/docs/start
GAQL ref:  https://developers.google.com/google-ads/api/fields/v22/overview
"""
import os
import time
from datetime import date
import requests
from dotenv import load_dotenv

load_dotenv()

_DEVELOPER_TOKEN     = os.environ["GOOGLE_ADS_DEVELOPER_TOKEN"]
_CLIENT_ID           = os.environ["GOOGLE_ADS_CLIENT_ID"]
_CLIENT_SECRET       = os.environ["GOOGLE_ADS_CLIENT_SECRET"]
_REFRESH_TOKEN       = os.environ["GOOGLE_ADS_REFRESH_TOKEN"]
_CUSTOMER_ID         = os.environ["GOOGLE_ADS_CUSTOMER_ID"].replace("-", "")
_LOGIN_CUSTOMER_ID   = os.environ.get("GOOGLE_ADS_LOGIN_CUSTOMER_ID", "").replace("-", "")
_API_VERSION         = os.environ.get("GOOGLE_ADS_API_VERSION", "v22")

_TOKEN_URL = "https://oauth2.googleapis.com/token"
_API_BASE  = f"https://googleads.googleapis.com/{_API_VERSION}"


class GoogleAdsAPIError(Exception):
    def __init__(self, status: int, body: str):
        self.status = status
        self.body   = body
        super().__init__(f"Google Ads API {status}: {body}")


class GoogleAdsClient:
    """
    Minimal Google Ads REST client. Uses GAQL via searchStream for reporting.

    Caller passes start/end as date objects; cost is returned in GBP (account
    currency — MowDirect Ads is in GBP, so cost_micros / 1_000_000 is GBP).
    """

    customer_id = _CUSTOMER_ID

    def __init__(self):
        self._access_token: str | None = None
        self._token_expiry: float      = 0

    def _ensure_token(self) -> None:
        if not self._access_token or time.time() >= self._token_expiry:
            self._access_token, self._token_expiry = self._refresh_access_token()

    def _refresh_access_token(self) -> tuple[str, float]:
        resp = requests.post(
            _TOKEN_URL,
            data={
                "client_id":     _CLIENT_ID,
                "client_secret": _CLIENT_SECRET,
                "refresh_token": _REFRESH_TOKEN,
                "grant_type":    "refresh_token",
            },
            headers={"Content-Type": "application/x-www-form-urlencoded"},
        )
        resp.raise_for_status()
        data = resp.json()
        return data["access_token"], time.time() + data["expires_in"] - 60

    def _headers(self) -> dict:
        self._ensure_token()
        headers = {
            "Authorization":   f"Bearer {self._access_token}",
            "developer-token": _DEVELOPER_TOKEN,
            "Content-Type":    "application/json",
        }
        if _LOGIN_CUSTOMER_ID:
            headers["login-customer-id"] = _LOGIN_CUSTOMER_ID
        return headers

    def search_stream(self, query: str) -> list[dict]:
        """
        Run a GAQL query against the configured customer and return all
        result rows (flattened across stream chunks).
        """
        url = f"{_API_BASE}/customers/{_CUSTOMER_ID}/googleAds:searchStream"
        resp = requests.post(url, headers=self._headers(), json={"query": query})
        if resp.status_code >= 400:
            raise GoogleAdsAPIError(resp.status_code, resp.text)

        rows: list[dict] = []
        # searchStream returns either a single object or an array of stream chunks.
        payload = resp.json()
        chunks = payload if isinstance(payload, list) else [payload]
        for chunk in chunks:
            rows.extend(chunk.get("results", []) or [])
        return rows

    def get_campaign_spend(self, start: date, end: date) -> list[dict]:
        """
        Fetch per-campaign spend/conversions/engagement for the given inclusive
        date range. Returns rows shaped for scripts/report aggregation:

            {campaign_id, campaign_name, campaign_type,
             spend_gbp, impressions, clicks,
             conversions, conversions_value}
        """
        query = f"""
            SELECT
              campaign.id,
              campaign.name,
              campaign.advertising_channel_type,
              metrics.cost_micros,
              metrics.impressions,
              metrics.clicks,
              metrics.conversions,
              metrics.conversions_value
            FROM campaign
            WHERE segments.date BETWEEN '{start.isoformat()}' AND '{end.isoformat()}'
        """

        rows: list[dict] = []
        for r in self.search_stream(query):
            campaign = r.get("campaign", {}) or {}
            metrics  = r.get("metrics", {}) or {}
            cost_micros = int(metrics.get("costMicros", 0) or 0)
            rows.append({
                "campaign_id":       campaign.get("id", ""),
                "campaign_name":     campaign.get("name", ""),
                "campaign_type":     campaign.get("advertisingChannelType", ""),
                "spend_gbp":         cost_micros / 1_000_000,
                "impressions":       int(metrics.get("impressions", 0) or 0),
                "clicks":            int(metrics.get("clicks", 0) or 0),
                "conversions":       float(metrics.get("conversions", 0) or 0),
                "conversions_value": float(metrics.get("conversionsValue", 0) or 0),
            })
        return rows


if __name__ == "__main__":
    # Smoke test: hit customer.descriptive_name — confirms auth + customer_id wiring.
    import json
    client = GoogleAdsClient()
    result = client.search_stream(
        "SELECT customer.descriptive_name, customer.currency_code FROM customer LIMIT 1"
    )
    print(json.dumps(result, indent=2))
